/*******************************************************************************
 * Copyright (c) 2007, 2019 IBM Corporation and Others
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Takashi ITOH - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_actf_util_win32_WindowUtil */

#ifndef _Included_org_eclipse_actf_util_win32_WindowUtil
#define _Included_org_eclipse_actf_util_win32_WindowUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_actf_util_win32_WindowUtil
 * Method:    SetLayeredWindowAttributes
 * Signature: (IICI)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_WindowUtil_SetLayeredWindowAttributes
  (JNIEnv *, jclass, jintLong, jint, jchar, jint);

#ifdef __cplusplus
}
#endif
#endif
