/*******************************************************************************
 * Copyright (c) 2007, 2019 IBM Corporation and Others
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Takashi ITOH - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_actf_util_win32_COMUtil */

#ifndef _Included_org_eclipse_actf_util_win32_COMUtil
#define _Included_org_eclipse_actf_util_win32_COMUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_actf_util_win32_COMUtil
 * Method:    VtblCall
 * Signature: (III)I
 */
#ifndef _WIN64
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__III
#else
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJI
#endif
  (JNIEnv *, jclass, jint, jintLong, jint);

/*
 * Class:     org_eclipse_actf_util_win32_COMUtil
 * Method:    VtblCall
 * Signature: (IIII)I
 */
#ifndef _WIN64
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IIII
#else
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJII
#endif
  (JNIEnv *, jclass, jint, jintLong, jint, jint);

/*
 * Class:     org_eclipse_actf_util_win32_COMUtil
 * Method:    VtblCall
 * Signature: (IIIII)I
 */
#ifndef _WIN64
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IIIII
#else
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIII
#endif
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jint);

/*
 * Class:     org_eclipse_actf_util_win32_COMUtil
 * Method:    VtblCall
 * Signature: (IIIIII)I
 */
#ifndef _WIN64
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IIIIII
#else
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIIII
#endif
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jint, jint);

/*
 * Class:     org_eclipse_actf_util_win32_COMUtil
 * Method:    VtblCall
 * Signature: (IIIIIII)I
 */
#ifndef _WIN64
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IIIIIII
#else
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIIIII
#endif
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jint, jint, jint);

/*
 * Class:     org_eclipse_actf_util_win32_COMUtil
 * Method:    VtblCall
 * Signature: (IIIIIIII)I
 */
#ifndef _WIN64
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IIIIIIII
#else
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIIIIII
#endif
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_eclipse_actf_util_win32_COMUtil
 * Method:    VtblCall
 * Signature: (IIIIIIIII)I
 */
#ifndef _WIN64
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IIIIIIIII
#else
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIIIIIII
#endif
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_eclipse_actf_util_win32_COMUtil
 * Method:    VtblCall
 * Signature: (IIIIIIIIII)I
 */
#ifndef _WIN64
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IIIIIIIIII
#else
	JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIIIIIIII
#endif
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jint, jint, jint, jint, jint, jint);

JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIIIJ
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jint, jlong);

JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIIJJ
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jlong, jlong);

JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIJJJ
  (JNIEnv *, jclass, jint, jintLong, jint, jlong, jlong, jlong);

JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIIJJJ
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jlong, jlong, jlong);

JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIIJJJJ
  (JNIEnv *, jclass, jint, jintLong, jint, jint, jlong, jlong, jlong, jlong);

JNIEXPORT jint JNICALL Java_org_eclipse_actf_util_win32_COMUtil_VtblCall__IJIJJJJJ
  (JNIEnv *, jclass, jint, jintLong, jint, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
